// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD31IwooZ0pj1zYIgrUiGkKoMdE7JNifpo',
    appId: '1:990674031942:web:18eed2e05056e422104147',
    messagingSenderId: '990674031942',
    projectId: 'databaseecen403-6fb45',
    authDomain: 'databaseecen403-6fb45.firebaseapp.com',
    databaseURL: 'https://databaseecen403-6fb45-default-rtdb.firebaseio.com',
    storageBucket: 'databaseecen403-6fb45.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtg2ZXbWgVvJCfWBB1Kk6zLEOtG9AhC5c',
    appId: '1:615238794922:android:54e4f92d8ba0e44f491ad3',
    messagingSenderId: '615238794922',
    projectId: 'databaseecen403',
    databaseURL: 'https://databaseecen403-default-rtdb.firebaseio.com',
    storageBucket: 'databaseecen403.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHYbrFB5gAEhJN7CRBtIJyA32PY1HmzQo',
    appId: '1:615238794922:ios:51bd6f97986a8948491ad3',
    messagingSenderId: '615238794922',
    projectId: 'databaseecen403',
    databaseURL: 'https://databaseecen403-default-rtdb.firebaseio.com',
    storageBucket: 'databaseecen403.firebasestorage.app',
    iosClientId: '615238794922-26kcjlv6gs7m0d6g3udl9bjtu0uk380c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHYbrFB5gAEhJN7CRBtIJyA32PY1HmzQo',
    appId: '1:615238794922:ios:51bd6f97986a8948491ad3',
    messagingSenderId: '615238794922',
    projectId: 'databaseecen403',
    databaseURL: 'https://databaseecen403-default-rtdb.firebaseio.com',
    storageBucket: 'databaseecen403.firebasestorage.app',
    iosClientId: '615238794922-26kcjlv6gs7m0d6g3udl9bjtu0uk380c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcQmKorsib7ubeZk7zKQ8wQoKKvIQidF4',
    appId: '1:615238794922:web:506cb8ac8e921901491ad3',
    messagingSenderId: '615238794922',
    projectId: 'databaseecen403',
    authDomain: 'databaseecen403.firebaseapp.com',
    databaseURL: 'https://databaseecen403-default-rtdb.firebaseio.com',
    storageBucket: 'databaseecen403.firebasestorage.app',
    measurementId: 'G-D302M6Q9KL',
  );
}